name: vclap2
channels:
  - intel
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8
  - django>=5.0
  - ca-certificates=2023.08.22
  - intel-openmp=2023.2.0
  - libcxx=15.0.7
  - libffi=3.4.4
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.11.5
  - readline=8.2
  - sqlite=3.41.2
  - tbb=2021.10.0
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.15.0
      - aliyun-python-sdk-kms==2.16.2
      - appdirs==1.4.4
      - appnope==0.1.3
      - asttokens==2.4.0
      - async-timeout==4.0.3
      - asynctest==0.13.0
      - attrs==23.1.0
      - audioread==3.0.1
      - backcall==0.2.0
      - blinker==1.6.2
      - brotlipy==0.7.0
      - cachetools==5.3.0
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==3.0.1
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.1.4
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==41.0.4
      - cycler==0.12.0
      - debugpy==1.8.0
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - entrypoints==0.4
      - eva-decord==0.6.1
      - executing==2.0.0
      - filelock==3.12.4
      - flit-core==3.9.0
      - fonttools==4.43.0
      - frozenlist==1.4.0
      - fsspec==2024.2.0
      - ftfy==6.1.3
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-auth==2.23.2
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - huggingface-hub
      - idna==3.4
      - imageio==2.33.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.2
      - ipykernel==6.25.2
      - ipython==8.16.1
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==0.10.0
      - joblib==1.2.0
      - jupyter-client==8.3.1
      - jupyter-core==5.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - librosa==0.10.1
      - llvmlite==0.41.1
      - markdown==3.4.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.2
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mmcv==1.7.2
      - mmengine==0.10.3
      - model-index==0.1.11
      - moviepy
      - mpmath==1.3.0
      - msclap==1.3.3
      - msgpack==1.0.8
      - multidict==6.0.4
      - nest-asyncio==1.5.8
      - networkx==3.1
      - numba==0.58.1
      - oauthlib==3.2.2
      - olefile==0.46
      - opencv-python==4.8.1.78
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==23.2
      - pandas==2.2.1
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==3.11.0
      - pooch==1.8.1
      - proglog==0.1.10
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pygments==2.16.1
      - pyjwt==2.8.0
      - pyopenssl==23.2.0
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2023.4
      - pyu2f==0.1.5
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - regex==2023.12.25
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - sentry-sdk==1.31.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - six==1.16.0
      - smmap==5.0.1
      - soundfile==0.12.1
      - soxr==0.3.7
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.4.0
      - threadpoolctl==3.1.0
      - tifffile==2023.9.26
      - timm==0.9.16
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchlibrosa==0.1.0
      - torchvision==0.16.2
      - tornado==6.3.3
      - tqdm
      - traitlets==5.11.1
      - transformers==4.38.2
      - typing-extensions==4.4.0
      - tzdata==2024.1
      - urllib3==1.26.14
      - wandb==0.15.11
      - wcwidth==0.2.13
      - werkzeug==2.2.2
      - wget==3.2
      - yacs==0.1.8
      - yapf==0.40.2
      - yarl==1.9.2
      - zipp==3.12.1
